module.exports = {
  /* =========================
     AUTH & ACCESS
  ========================= */
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  ACCESS_DENIED: "ACCESS_DENIED",
  ROLE_NOT_ALLOWED: "ROLE_NOT_ALLOWED",

  /* =========================
     VALIDATION
  ========================= */
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  INVALID_QUERY_PARAMS: "INVALID_QUERY_PARAMS",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

  /* =========================
     RESOURCE / DB
  ========================= */
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  RESOURCE_IN_USE: "RESOURCE_IN_USE",
  RESOURCE_ALREADY_DELETED: "RESOURCE_ALREADY_DELETED",

  /* =========================
     DATABASE (IMPORTANT)
  ========================= */
  DATABASE_ERROR: "DATABASE_ERROR",
  DATABASE_CONNECTION_FAILED: "DATABASE_CONNECTION_FAILED",
  DATABASE_TIMEOUT: "DATABASE_TIMEOUT",
  DATABASE_DISCONNECTED: "DATABASE_DISCONNECTED",

  /* =========================
     BUSINESS RULES
  ========================= */
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  INVALID_STATE: "INVALID_STATE",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  ENTRY_ALREADY_SETTLED: "ENTRY_ALREADY_SETTLED",

  /* =========================
     MEDIA / FILE UPLOAD
  ========================= */
  IMAGE_UPLOAD_FAILED: "IMAGE_UPLOAD_FAILED",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",

  /* =========================
     AUTH FLOW (OTP / LOGIN)
  ========================= */
  OTP_REQUIRED: "OTP_REQUIRED",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_INVALID: "OTP_INVALID",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",

  /* =========================
     SYSTEM
  ========================= */
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
};
